### ISSUE TITLE
Silent runtime failure due to macro

### ISSUE THREAD

**Issue by ravemir** [MoemenMostafa/cordova-plugin-sfauthenticationsession#3]
Hello,

I believe the following line could mislead people into thinking that their app will contain access to the SFAuthentication API, even when iOS SDK 11 is not installed:
https://github.com/MoemenMostafa/cordova-plugin-sfauthenticationsession/blob/70c34e1cabca59c9e0384ecf6af7b159fe1489c4/src/ios/SFAuthSession.m#L4

My suggestion would be to remove it; just allow the failure to happen at build time, in order for people to be aware they need iOS SDK 11 properly set-up before continuing. Otherwise, they could be developing the app, only to find the odd behavior after a lot more troubleshooting.

Makes sense?

**Comment by MoemenMostafa** [comment]
Hi @ravemir,
I think this make sense, I will remove this line and update the documentation to state that iOS SDK 11 is a prerequisite.

**Comment by ravemir** [comment]
Great! Thanks for the prompt reply!

**Comment by ravemir** [comment]
Hello, @MoemenMostafa,

Any news on this? This looks like a relatively straightforward adjustment.

Do let me know if you need any help validating afterwards!

Thanks in advance!
