### ISSUE TITLE
Deprecated on iOS 12

### ISSUE THREAD

**Issue by davidreher** [MoemenMostafa/cordova-plugin-sfauthenticationsession#4]
Hey,
SFAuthenticationSession is now [deprecated](https://developer.apple.com/documentation/safariservices/sfauthenticationsession). Are there any plans on supporting the now favoured ASWebAuthenticationSession? Or will there be a new plugin for this?

**Comment by MoemenMostafa** [comment]
I think a new plugin would be better. It should be straight forward. Will let u know.

**Comment by FiReBlUe45** [comment]
Hello, 
Did you find a solution?
I use the ionic framework and I will need a solution that allows sessions and cookies to be shared between safari view controler API and safari.
Thanks you
